---
- name: Configurar o sistema no ambiente chroot
  hosts: localhost
  become: yes
  vars_files:
    - 99-vars.yaml
  tasks:
    - name: Adicionar o usuário "{{ USERNAME }}"
      user:
        name: "{{ USERNAME }}"
        comment: "{{ USER_COMMENT }}"
        shell: "{{ USER_SHELL }}"
        groups: "{{ USER_GROUPS | join(',') }}"
        password: "{{ user_password | password_hash('sha512') }}"
        # create_home: yes

    - name: Copiar /proc/mounts para /etc/fstab
      copy:
        remote_src: yes
        src: /proc/mounts
        dest: /etc/fstab

    - name: Remover entradas desnecessárias de /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^(devpts|tmpfs|proc|sysfs)'
        state: absent

    - name: Adicionar entrada tmpfs para /tmp no fstab
      blockinfile:
        path: /etc/fstab
        block: |
          tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0

    - name: Criando uma swapfile
      when: add_swapfile | lower == 'y'
      block:
        - name: Pré-alocando espaço para a swapfile
          command: fallocate -l {{ SWAPFILE_SIZE }} /swapfile

        - name: Mudando as permições
          command: chmod 600 /swapfile

        - name: Setando uma area de swap
          command: mkswap /swapfile

        - name: Ativando a swap
          command: swapon /swapfile

        - name: Adicionando a swap ao /etc/fstab
          blockinfile:
            path: /etc/fstab
            block: |
              /swapfile none swap sw 0 0

        # TODO: add hibernation

    - name: Instalar pacotes adicionais
      command: xbps-install -Sy {{ item }}
      loop: "{{ PACKAGES }}"

    - name: Habilitar serviços
      command: ln -s /etc/sv/{{ item }} /etc/runit/runsvdir/default/
      loop: "{{ SERVICES }}"

    - name: Configurar grub no sistema
      command: grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="Void"

    - name: Reconfigurar todos os pacotes
      command: xbps-reconfigure -fa
